# Generated by Django 2.0.6 on 2018-06-25 14:20

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_number', models.PositiveIntegerField(default=0, verbose_name='store number')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('state', localflavor.us.models.USStateField(max_length=2, verbose_name='us state')),
                ('zip', localflavor.us.models.USZipCodeField(max_length=10, verbose_name='zip code')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='provider phone')),
                ('website', models.URLField(blank=True, max_length=255, verbose_name='provider website')),
                ('email', models.EmailField(error_messages={'unique': 'A provider with that email already exists.'}, max_length=254, unique=True, verbose_name='provider email address')),
                ('operating_hours', models.CharField(max_length=255, verbose_name='operating hours')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('insurance_accepted', models.TextField(blank=True, verbose_name='insurance accepted')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('long', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('start_date', models.DateTimeField(null=True, verbose_name='start date')),
                ('end_date', models.DateTimeField(null=True, verbose_name='start date')),
                ('walkins_accepted', models.NullBooleanField(verbose_name='walkins accepted')),
            ],
            options={
                'verbose_name': 'provider',
                'verbose_name_plural': 'providers',
            },
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='organization phone'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, max_length=255, verbose_name='organization website'),
        ),
        migrations.AddField(
            model_name='provider',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='medications.Organization'),
        ),
    ]
