# Generated by Django 2.0.6 on 2018-06-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_auto_20180625_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='long',
            new_name='lng',
        ),
    ]
