# Generated by Django 2.0.6 on 2018-06-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_auto_20180625_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='change_coordinates',
            field=models.BooleanField(default=False, help_text='Check this if you want the application to recalculate the coordinates. Used in case address has been changed', verbose_name='change coordinates'),
        ),
    ]
