# Generated by Django 2.0.6 on 2018-06-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_provider_change_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='medication name')),
                ('ndc', models.CharField(max_length=32, unique=True, verbose_name='national drug code')),
            ],
            options={
                'verbose_name': 'medication',
                'verbose_name_plural': 'medications',
            },
        ),
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(max_length=255, verbose_name='provider address'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='city',
            field=models.CharField(max_length=255, verbose_name='provider city'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=255, verbose_name='provider name'),
        ),
    ]
