# Generated by Django 2.0.6 on 2018-06-26 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0007_providermedicationthrough'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermedicationthrough',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
    ]
