# Generated by Django 2.0.6 on 2018-06-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0008_auto_20180626_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='insurance_accepted',
            field=models.BooleanField(default=False, verbose_name='insurance accepted'),
        ),
    ]
