# Generated by Django 2.0.6 on 2018-06-26 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0009_auto_20180626_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providermedicationthrough',
            name='start_date',
        ),
        migrations.AddField(
            model_name='providermedicationthrough',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date of addition/update of this medication', verbose_name='date'),
        ),
    ]
