# Generated by Django 2.0.6 on 2018-06-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0011_temporaryfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A provider with that email already exists.'}, max_length=254, null=True, unique=True, verbose_name='provider email address'),
        ),
    ]
