# Generated by Django 2.0.6 on 2018-07-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0012_auto_20180628_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(default=None, max_length=255, verbose_name='organization name'),
        ),
    ]
