# Generated by Django 2.0.6 on 2018-07-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0013_existingmedication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='existingmedication',
            options={'verbose_name': 'existing medication', 'verbose_name_plural': 'existing medications'},
        ),
        migrations.AlterField(
            model_name='existingmedication',
            name='ndc',
            field=models.CharField(max_length=32, verbose_name='national drug code'),
        ),
    ]
