# Generated by Django 2.0.6 on 2018-07-06 11:58

from django.db import migrations
import localflavor.us.models
import medications.validators


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0013_auto_20180705_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='state',
            field=localflavor.us.models.USStateField(max_length=2, validators=[medications.validators.validate_state], verbose_name='us state'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='zip',
            field=localflavor.us.models.USZipCodeField(max_length=10, validators=[medications.validators.validate_zip], verbose_name='zip code'),
        ),
    ]
