# Generated by Django 2.0.6 on 2018-07-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0015_auto_20180704_1407'),
        ('medications', '0014_auto_20180706_1158'),
    ]

    operations = [
    ]
