# Generated by Django 2.0.6 on 2018-07-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0016_merge_20180706_1242'),
        ('medications', '0016_merge_20180706_1256'),
    ]

    operations = [
    ]
