# Generated by Django 2.0.6 on 2018-07-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0018_provider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermedicationthrough',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation date', verbose_name='date'),
        ),
    ]
