# Generated by Django 2.0.6 on 2018-07-25 09:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0023_auto_20180718_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(blank=True, max_length=255, verbose_name='us county name')),
                ('geometry', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='geometry')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='medications.State')),
            ],
            options={
                'verbose_name': 'county',
                'verbose_name_plural': 'counties',
            },
        ),
    ]
