# Generated by Django 2.0.6 on 2018-07-27 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0025_state_state_us_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'medication name',
                'verbose_name_plural': 'medication names',
            },
        ),
        migrations.AddField(
            model_name='medication',
            name='medication_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='medications.MedicationName'),
        ),
    ]
