# Generated by Django 2.0.6 on 2018-07-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0026_auto_20180727_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='geometry',
        ),
    ]
