# Generated by Django 2.0.6 on 2018-07-30 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0029_auto_20180727_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='zipcode',
            name='geometry',
        ),
    ]
