# Generated by Django 2.0.6 on 2018-07-30 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0031_auto_20180730_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipcode',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_zipcodes', to='medications.County'),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_zipcodes', to='medications.State'),
        ),
    ]
