# Generated by Django 2.0.6 on 2018-07-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0032_auto_20180730_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='county_name_slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='us county name slug'),
        ),
    ]
