# Generated by Django 2.0.6 on 2018-07-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0033_county_county_name_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='county_id',
            field=models.PositiveIntegerField(null=True, verbose_name='county us id'),
        ),
        migrations.AddField(
            model_name='county',
            name='geo_id',
            field=models.PositiveIntegerField(null=True, verbose_name='geo id'),
        ),
    ]
