# Generated by Django 2.0.6 on 2018-07-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0034_auto_20180731_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipcode',
            name='county',
        ),
        migrations.AddField(
            model_name='zipcode',
            name='counties',
            field=models.ManyToManyField(null=True, related_name='county_zipcodes', to='medications.County'),
        ),
    ]
