# Generated by Django 2.0.6 on 2018-08-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0035_auto_20180731_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='lat',
            field=models.CharField(blank=True, null=True, max_length=250, verbose_name='latitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='lng',
            field=models.CharField(blank=True, null=True, max_length=250, verbose_name='longitude'),
            preserve_default=False,
        ),
    ]
