# Generated by Django 2.0.6 on 2018-08-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0036_auto_20180801_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='relate_related_zipcode',
            field=models.BooleanField(default=False, help_text='Check if you need the system to relate a new zipcode object to this provider. Generally you should use this only if you are an admin changing the direction of this provider', verbose_name='relate zipcode'),
        ),
    ]
