# Generated by Django 2.0.6 on 2018-08-09 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0037_provider_relate_related_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='00', help_text='code used by the NCPDP to identify the type of provider.This code is a charfield cause it should be 01, 02, 03... and no more than 2 digits', max_length=2, verbose_name='provider type code')),
                ('name', models.CharField(max_length=255, verbose_name='provider name')),
            ],
        ),
    ]
