# Generated by Django 2.0.6 on 2018-08-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0038_auto_20180809_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='type',
        ),
    ]
