# Generated by Django 2.0.6 on 2018-08-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0040_provider_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='00', help_text='code used by the NCPDP to identify the category of provider.This code is a charfield cause it should be 01, 02, 03... and no more than 2 digits', max_length=2, verbose_name='provider category code')),
                ('name', models.CharField(max_length=255, verbose_name='category name')),
            ],
        ),
        migrations.AlterField(
            model_name='providertype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='type name'),
        ),
        migrations.AddField(
            model_name='provider',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='medications.ProviderCategory'),
        ),
    ]
