# Generated by Django 2.0.6 on 2018-08-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0042_auto_20180809_1229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryFile',
        ),
    ]
