# Generated by Django 2.0.6 on 2018-08-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0043_delete_temporaryfile'),
        ('medications', '0038_provider_geo_localization'),
    ]

    operations = [
    ]
