# Generated by Django 2.0.6 on 2018-08-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0046_auto_20180827_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='population',
            field=models.PositiveIntegerField(null=True, verbose_name='population'),
        ),
        migrations.AddField(
            model_name='state',
            name='population',
            field=models.PositiveIntegerField(null=True, verbose_name='population'),
        ),
        migrations.AddField(
            model_name='zipcode',
            name='population',
            field=models.PositiveIntegerField(null=True, verbose_name='population'),
        ),
    ]
