# Generated by Django 2.0.6 on 2018-10-01 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0049_auto_20180928_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='last_import_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Last time this provider uploaded new information.', verbose_name='last import date'),
            preserve_default=False,
        ),
    ]
