# Generated by Django 2.0.6 on 2018-10-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0050_provider_last_import_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
