# Generated by Django 2.0.6 on 2018-10-03 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0051_provider_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='home_delivery',
            field=models.BooleanField(default=False, verbose_name='home delivery'),
        ),
        migrations.AddField(
            model_name='provider',
            name='home_delivery_info_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='home delivery info url'),
        ),
        migrations.AlterField(
            model_name='medicationndc',
            name='medication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ndc_codes', to='medications.Medication'),
        ),
    ]
