# Generated by Django 2.0.6 on 2018-10-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0054_auto_20181026_1320'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicationndc',
            index=models.Index(fields=['ndc'], name='medications_ndc_4d8d2d_idx'),
        ),
    ]
