# Generated by Django 2.0.6 on 2018-11-29 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0057_auto_20181128_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationDosage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'medication dosage',
                'verbose_name_plural': 'medication dosages',
            },
        ),
        migrations.CreateModel(
            name='MedicationMedicationNameMedicationDosageThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_medications', to='medications.Medication')),
                ('medication_dosage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_medication_dosages', to='medications.MedicationDosage')),
                ('medication_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_medication_names', to='medications.MedicationName')),
            ],
            options={
                'verbose_name': 'medication name medication dosage relation',
                'verbose_name_plural': 'medication name medication dosage relations',
            },
        ),
        migrations.CreateModel(
            name='MedicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'medication dosage',
                'verbose_name_plural': 'medication dosages',
            },
        ),
        migrations.CreateModel(
            name='MedicationTypeMedicationNameThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_names', to='medications.MedicationName')),
                ('medication_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_types', to='medications.MedicationType')),
            ],
            options={
                'verbose_name': 'medication name medication type relation',
                'verbose_name_plural': 'medication name medication type relations',
            },
        ),
        migrations.AddIndex(
            model_name='medicationtypemedicationnamethrough',
            index=models.Index(fields=['medication_type_id', 'medication_name_id'], name='medications_medicat_b77cea_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationmedicationnamemedicationdosagethrough',
            index=models.Index(fields=['medication_name_id', 'medication_dosage_id'], name='medications_medicat_d085e2_idx'),
        ),
    ]
