# Generated by Django 2.0.9 on 2018-12-08 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0058_auto_20181129_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationNameEquivalence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equivalent_medication_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equivalent_medication_names', to='medications.MedicationName')),
                ('medication_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medication_name', to='medications.MedicationName')),
            ],
            options={
                'verbose_name': 'equivalent medication name',
                'verbose_name_plural': 'equivalent medication names',
            },
        ),
        migrations.AlterField(
            model_name='medicationmedicationnamemedicationdosagethrough',
            name='medication_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_dosages', to='medications.MedicationName'),
        ),
    ]
