# Generated by Django 2.0.9 on 2018-12-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0059_auto_20181208_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='vaccine_finder_id',
            field=models.PositiveIntegerField(null=True, verbose_name='vaccine finder id'),
        ),
        migrations.AddField(
            model_name='provider',
            name='vaccine_finder_id',
            field=models.PositiveIntegerField(null=True, verbose_name='vaccine finder id'),
        ),
    ]
