# Generated by Django 2.0.9 on 2018-12-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0060_auto_20181220_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='vaccine_finder_type',
            field=models.PositiveIntegerField(null=True, verbose_name='vaccine finder type'),
        ),
    ]
