# Generated by Django 2.0.9 on 2018-12-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0061_provider_vaccine_finder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationdosage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
    ]
