# Generated by Django 2.0.9 on 2019-01-09 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0063_auto_20190108_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='active_provider_count',
        ),
        migrations.RemoveField(
            model_name='county',
            name='total_provider_count',
        ),
        migrations.RemoveField(
            model_name='state',
            name='active_provider_count',
        ),
        migrations.RemoveField(
            model_name='state',
            name='total_provider_count',
        ),
        migrations.RemoveField(
            model_name='zipcode',
            name='active_provider_count',
        ),
        migrations.RemoveField(
            model_name='zipcode',
            name='total_provider_count',
        ),
    ]
