# Generated by Django 2.0.9 on 2019-01-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0065_auto_20190110_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermedicationndcthrough',
            name='latest',
            field=models.BooleanField(db_index=True, default=False, verbose_name='latest'),
        ),
    ]
