# Generated by Django 2.0.9 on 2019-01-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0066_auto_20190110_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='dosage',
            field=models.CharField(max_length=255, null=True, verbose_name='medication dosage'),
        ),
    ]
