# Generated by Django 2.0.9 on 2019-01-17 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0068_provider_related_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providermedicationndcthrough',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='providermedicationndcthrough',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date', verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='providermedicationndcthrough',
            name='creation_date',
            field=models.DateTimeField(help_text='Creation date', verbose_name='creation date'),
        ),
    ]
