# Generated by Django 2.0.9 on 2019-01-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0071_county_centroid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='centroid',
        ),
        migrations.AddField(
            model_name='state',
            name='center_lat',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='center latitude'),
        ),
        migrations.AddField(
            model_name='state',
            name='center_lng',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='center longitude'),
        ),
    ]
