# Generated by Django 2.0.6 on 2018-08-22 15:13

from django.db import migrations


def create_epidemic_object(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Epidemic = apps.get_model('epidemic', 'Epidemic')
    if not Epidemic.objects.exists():
        Epidemic.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ('epidemic', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_epidemic_object),
    ]
