# Generated by Django 2.0.9 on 2019-01-18 16:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemic', '0002_auto_20180822_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='epidemic',
            name='content',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
