# Generated by Django 2.0.6 on 2018-07-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0002_user_is_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_test',
        ),
    ]
