# Generated by Django 2.0.6 on 2018-08-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0003_remove_user_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission_level',
            field=models.CharField(choices=[('nl', 'National level permission'), ('sl', 'State level permission')], default='sl', max_length=2, verbose_name='permission level'),
        ),
    ]
