# Generated by Django 2.0.6 on 2018-08-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0004_user_permission_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invitation_mail_sent',
            field=models.BooleanField(default=False, help_text='Designates whether the invitation mail for this user  has been sent', verbose_name='invitation mail sent'),
        ),
    ]
