# Generated by Django 2.0.6 on 2018-08-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0006_user_invitation_mail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, help_text='role this user has in the related organization', max_length=250, verbose_name='role in organization'),
        ),
    ]
