# Generated by Django 2.0.6 on 2018-08-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0006_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='used_invitation_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='used invitation code'),
        ),
    ]
