# Generated by Django 2.0.6 on 2018-08-29 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0047_auto_20180828_1258'),
        ('auth_ex', '0007_user_used_invitation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='medications.State'),
        ),
    ]
