# Generated by Django 2.0.6 on 2018-08-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0007_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='secret',
        ),
    ]
